// src/components/Products.js


const criaTamanho = function (tamanho, disponivel) {
  return {
    tamanho: tamanho,
    disponivel: disponivel,
  };
};
const produtos = [
  {
    id: 1,
    nome: "Jaqueta Jeans Plus Size Masculina Classic - Mais Pano",
    cores: ["Azul", "Cinza", "Preto"],
    imagens: ["https://i.imgur.com/Z2gex7E.png"],
    desconto: 10,
    preco: 120,
    categoria: "Masculino",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", true),
    ],
    descricao: "Jaqueta Masculina",
    promocao: false,
    infoTecnicas: [
      "Material: Jeans de alta qualidade",
      "Tamanhos disponíveis: GG, XGG, XGGG",
      "Fechamento: Zíper e botões",
      "Estilo: Casual",
      "Origem: Nacional",
    ],
    infoAdicionais: [
      "Ideal para o clima frio",
      "Design moderno e robusto",
      "Acabamento impecável",
      "Tecido durável e confortável",
      "Perfeito para o uso diário",
    ],
  },
  {
    id: 2,
    nome: "Blusa Feminina Cetim Brenda",
    cores: ["Preto", "Cinza", "Marrom"],
    imagens: [
      "https://i.imgur.com/SLOdxW6.jpeg",//resize
      "https://dcdn.mitiendanube.com/stores/001/266/478/products/whatsapp-image-2021-07-18-at-00-31-5351-0eca1c9f3b87a81a0416265793267884-640-0.jpeg", 
      "https://i.imgur.com/SLOdxW6.jpeg",//resize
    ],
    desconto: 10,
    preco: 80,
    categoria: "Feminino",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", true),
    ],
    descricao: "Blusa Feminina",
    promocao: false,
    infoTecnicas: [
      "Material: Cetim",
      "Tamanhos disponíveis: P, M, G, GG, EG",
      "Fechamento: Botões nas costas",
      "Estilo: Elegante",
      "Origem: Nacional",
    ],
    infoAdicionais: [
      "Tecido suave e confortável",
      "Ideal para eventos formais",
      "Design sofisticado",
      "Fácil de combinar com outras peças",
      "Disponível em várias cores",
    ],
  },
  {
    id: 3,
    nome: "Blusão Moletom Infantil Pantera Negra Marvel",
    cores: ["Cinza", "Preto", "Azul"],
    imagens: [
      "https://torratorra.vtexassets.com/arquivos/ids/951990/35222000331136-1.jpg?v=638212272383370000",
      "https://i.imgur.com/eVSdvra.png",//resize
    ],
    desconto: 17,
    preco: 78,
    categoria: "Infantil",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", false),
      criaTamanho("EG", false),
    ],
    descricao: "Moletom Infantil",
    promocao: true,
    infoTecnicas: [
      "Material: Moletom 100% algodão",
      "Tamanhos disponíveis: 2-3 anos, 4-5 anos, 6-7 anos",
      "Estilo: Casual",
      "Impressão: Pantera Negra Marvel",
      "Origem: Nacional",
    ],
    infoAdicionais: [
      "Tecido macio e quente",
      "Ideal para o inverno",
      "Design divertido e moderno",
      "Resistente a lavagem",
      "Confortável para o uso diário",
    ],
  },
  {
    id: 4,
    nome: "Conjunto Infantil Masculino Califórnia",
    cores: ["Cinza", "Preto", "Azul", "Violeta"],
    imagens: [
      "https://i.imgur.com/V416nC3.png",//resize
      "https://i.imgur.com/TWluiaZ.png",
      "https://i.imgur.com/V416nC3.png",//resize
      "https://i.pinimg.com/736x/90/2e/ea/902eea71bf4a1274389bc9cdaf9d5bc2.jpg",
      "https://http2.mlstatic.com/D_NQ_NP_625553-MLB51149656494_082022-W.jpg",
      "https://ph-cdn3.ecosweb.com.br/imagens01/foto/roupa-para-menino/conjunto-verao/conjunto-infantil-masculino-branco_624500_600_1.jpg",
      "https://http2.mlstatic.com/D_NQ_NP_672390-MLB44280919897_122020-F.jpg",
      "https://ph-cdn3.ecosweb.com.br/imagens01/foto/roupa-para-menino/conjunto-verao/conjunto-marisol-bege-menino_596107_600_1.jpg",
    ],
    desconto: 13,
    preco: 178,
    categoria: "Infantil",
    opcao: [
      criaTamanho("P", false),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", false),
    ],
    descricao: "Conjunto Infantil Masculino",
    promocao: true,
    infoTecnicas: [
      "Material: Algodão e poliéster",
      "Tamanhos disponíveis: 2-3 anos, 4-5 anos, 6-7 anos",
      "Fechamento: Elástico e cordão",
      "Estilo: Casual",
      "Origem: Nacional",
      "Material: Algodão e poliéster",
      "Tamanhos disponíveis: 2-3 anos, 4-5 anos, 6-7 anos",
      "Fechamento: Elástico e cordão",
      "Estilo: Casual",
      "Origem: Nacional",
      "Material: Algodão e poliéster",
      "Tamanhos disponíveis: 2-3 anos, 4-5 anos, 6-7 anos",
      "Fechamento: Elástico e cordão",
      "Estilo: Casual",
    ],
    infoAdicionais: [
      "Conjunto confortável e estiloso",
      "Ideal para o dia a dia",
      "Fácil de vestir e remover",
      "Tecido respirável e resistente",
      "Disponível em cores variadas",
      "Conjunto confortável e estiloso",
      "Ideal para o dia a dia",
      "Fácil de vestir e remover",
      "Tecido respirável e resistente",
      "Disponível em cores variadas",
      "Conjunto confortável e estiloso",
      "Ideal para o dia a dia",
      "Fácil de vestir e remover",
      "Tecido respirável e resistente",
      "Disponível em cores variadas",
      "Conjunto confortável e estiloso",
      "Ideal para o dia a dia",
      "Fácil de vestir e remover",
      "Tecido respirável e resistente",
      "Disponível em cores variadas",
      "Conjunto confortável e estiloso",
      "Ideal para o dia a dia",
      "Fácil de vestir e remover",
      "Tecido respirável e resistente",
      "Disponível em cores variadas",
      "Fácil de vestir e remover",
      "Tecido respirável e resistente",
      "Disponível em cores variadas",
      "Conjunto confortável e estiloso",
      "Ideal para o dia a dia",
      "Fácil de vestir e remover",
      "Tecido respirável e resistente",
      "Disponível em cores variadas",
      "Conjunto confortável e estiloso",
      "Ideal para o dia a dia",
      "Fácil de vestir e remover",
      "Tecido respirável e resistente",
      "Disponível em cores variadas",
      "Ideal para o dia a dia",
      "Fácil de vestir e remover",
      "Tecido respirável e resistente",
      "Disponível em cores variadas",
      "Conjunto confortável e estiloso",
      "Ideal para o dia a dia",
      "Fácil de vestir e remover",
      "Tecido respirável e resistente",
      "Disponível em cores variadas",
    ],
  },
  {
    id: 5,
    nome: "Calça Masculina Slim Flexível - Tech Comfort",
    cores: ["Branco", "Azul-Escuro", "Cinza", "Preto"],
    imagens: [
      "https://fragamaia.com/cdn/shop/products/calca-masculina-comfort-flex-slim-1004-754.webp?v=1679331271",
    ],
    desconto: 10,
    preco: 215,
    categoria: "Masculino",
    opcao: [
      {
        tamanho: "34",
        disponivel: true,
      },
      {
        tamanho: "36",
        disponivel: true,
      },
      criaTamanho("38", true),
      criaTamanho("40", true),
      criaTamanho("42", false),
      criaTamanho("44", true),
      criaTamanho("46", true),
      criaTamanho("48", false),
      criaTamanho("50", true),
      criaTamanho("52", false),
      criaTamanho("54", false),
      criaTamanho("56", true),
      criaTamanho("58", false),
      criaTamanho("60", true),
      criaTamanho("62", false),
    ],
    descricao: "Calça Masculina Slim",
    promocao: false,
    infoTecnicas: [
      "Material: Algodão e elastano",
      "Tamanhos disponíveis: 36, 38, 40",
      "Fechamento: Zíper e botão",
      "Estilo: Slim fit",
      "Origem: Nacional",
    ],
    infoAdicionais: [
      "Conforto e flexibilidade",
      "Design moderno e ajustado",
      "Ideal para o uso diário",
      "Tecido resistente e durável",
      "Disponível em tons clássicos",
    ],
  },
  {
    id: 6,
    nome: "Saia feminina midi plissada lisa com forro poliéster",
    cores: ["Marrom", "Preto", "Azul"],
    imagens: [
      "https://a-static.mlcdn.com.br/450x450/saia-feminina-midi-plissada-lisa-com-forro-poliester-moda-blogueira-filo-modas/lojamatos1/8cff46ca208f11ed95324201ac185019/fbd7a83aff3ed9fff07a8c823664101d.jpeg",
    ],
    desconto: 25,
    preco: 199,
    categoria: "Feminina",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", false),
      criaTamanho("GG", true),
      criaTamanho("EG", false),
    ],
    descricao: "Saia feminina",
    promocao: true,
    infoTecnicas: [
      "Material: Poliéster com forro",
      "Tamanhos disponíveis: P, M, G",
      "Estilo: Midi plissada",
      "Fechamento: Zíper lateral",
      "Origem: Nacional",
    ],
    infoAdicionais: [
      "Saia elegante e feminina",
      "Ideal para eventos e saídas",
      "Design plissado e fluido",
      "Fácil de combinar com blusas",
      "Tecido resistente e confortável",
    ],
  },
  {
    id: 7,
    nome: "Kit roupas infantil / Lançamento de Verão 5 Conjuntos ",
    cores: ["Branco", "Verde", "Vermelho", "Amarelo"],
    imagens: [
      "https://images-americanas.b2w.io/produtos/3709245831/imagens/kit-roupas-infantil-lancamento-de-verao-5-conjuntos-manga-curta-de-menino-do-4-16-anos/3709245831_1_large.jpg",
    ],
    desconto: 10,
    preco: 150,
    categoria: "Infantil",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", false),
      criaTamanho("EG", false),
    ],
    descricao: "Kit roupas infantil",
    promocao: false,
    infoTecnicas: [
      "Material: Algodão e poliéster",
      "Tamanhos disponíveis: 4-5 anos, 6-7 anos, 8-9 anos",
      "Inclui: 5 conjuntos variados",
      "Estilo: Casual e verão",
      "Origem: Nacional",
    ],
    infoAdicionais: [
      "Kit completo para verão",
      "Design colorido e alegre",
      "Ideal para crianças ativas",
      "Tecido leve e respirável",
      "Fácil de lavar e manter",
    ],
  },
  {
    id: 8,
    nome: "Terno Masculino Preto Social Traje",
    cores: ["Cinza", "Preto"],
    imagens: [
      "https://images.tcdn.com.br/img/img_prod/914261/traje_lisboa_791_1_dcdae78afb170bf16797f4b00673a244.jpg",
      "https://i.imgur.com/CuMnhJc.png", //resize
    ],
    desconto: 15,
    preco: 399,
    categoria: "Masculino",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", true),
    ],
    descricao: "Terno Masculino",
    promocao: true,
    infoTecnicas: [
      "Material: Poliéster e viscose",
      "Tamanhos disponíveis: 46, 48, 50",
      "Fechamento: Botões e zíper",
      "Estilo: Social",
      "Origem: Nacional",
    ],
    infoAdicionais: [
      "Ideal para eventos formais",
      "Design sofisticado e elegante",
      "Fácil ajuste e conforto",
      "Tecido de alta qualidade",
      "Disponível em duas cores",
    ],
  },
  {
    id: 9,
    nome: "Casaco de terno feminino solto e descontraído",
    cores: ["Laranja", "Marrom", "Preto", "Cinza"],
    imagens: [
      "https://ae01.alicdn.com/kf/S3c3b35c72170455f94056fbac6755eafp.jpg_640x640Q90.jpg_.webp",
    ],
    desconto: 10,
    preco: 150,
    categoria: "Feminino",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", false),
      criaTamanho("EG", true),
    ],
    descricao: "Casaco de terno feminino",
    promocao: false,
    infoTecnicas: [
      "Material: Algodão e poliéster",
      "Tamanhos disponíveis: P, M, G",
      "Fechamento: Botões frontais",
      "Estilo: Solto e descontraído",
      "Origem: Nacional",
    ],
    infoAdicionais: [
      "Casaco leve e confortável",
      "Ideal para ocasiões casuais",
      "Design moderno e descontraído",
      "Tecido resistente e durável",
      "Disponível em cores vivas",
    ],
  },
  {
    id: 10,
    nome: "Terno Infantil Criança Kit Completo",
    cores: ["Branco", "Cinza", "Preto", "Azul"],
    imagens: [
      "https://socialkids.com.br/medias/2-4.jpg",
      "https://i.imgur.com/FD7YtuX.jpeg", //resize
    ],
    desconto: 23,
    preco: 189,
    categoria: "Infantil",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", false),
      criaTamanho("GG", true),
      criaTamanho("EG", false),
    ],
    descricao: "Terno Infantil",
    promocao: true,
    infoTecnicas: [
      "Material: Poliéster e viscose",
      "Tamanhos disponíveis: 2-3 anos, 4-5 anos, 6-7 anos",
      "Fechamento: Botões e zíper",
      "Estilo: Formal",
      "Origem: Nacional",
    ],
    infoAdicionais: [
      "Terno completo para crianças",
      "Design elegante e sofisticado",
      "Ideal para eventos especiais",
      "Fácil ajuste e conforto",
      "Tecido de alta qualidade",
    ],
  },
  {
    id: 11,
    nome: "Moletom Masculino Bordô - Ralph Lauren",
    cores: ["Violeta", "Roxo", "Cinza", "Bordô"],
    imagens: [
      "https://images.tcdn.com.br/img/img_prod/945252/moletom_ralph_lauren_canguru_masculino_bordo_1785_1_9fba92142799d14cece0ed03ee8cc5bd.jpg",
      "https://i.imgur.com/OMUuIyM.png", //resize
    ],
    desconto: 27,
    preco: 199,
    categoria: "Masculino",
    opcao: [
      criaTamanho("P", false),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", false),
    ],
    descricao: "Moletom Masculino",
    promocao: true,
    infoTecnicas: [
      "Composição: 80% algodão, 20% poliéster.",
      "Tamanho: Disponível em P, M, G, GG.",
      "Lavagem: Lavar à máquina em água fria.",
      "Fechamento: Canguru com capô.",
      "Detalhes: Acabamento bordado Ralph Lauren.",
    ],
    infoAdicionais: [
      "Ideal para dias frios.",
      "Confortável e resistente.",
      "Cores vibrantes e modernas.",
      "Estilo casual e esportivo.",
      "Marca renomada e de alta qualidade.",
    ],
  },
  {
    id: 12,
    nome: "Cobertor King Jolitex Kyor Plus Nantes 2,20 X 2,40m",
    cores: [
      "Violeta",
      "Roxo",
      "Cinza",
      "Branco",
      "Verde",
      "Azul",
      "Rosa",
      "Vermelho",
      "Amarelo",
      "Preto",
    ],
    imagens: [
      "https://www.bing.com/th?id=OPHS.uoXc0qMBqWEbLA474C474&o=5&pid=21.1&w=160&h=160&qlt=100&dpr=1,3&c=8&pcl=f5f5f5",
    ],
    desconto: 47,
    preco: 429,
    categoria: "Outlet",
    opcao: [
      criaTamanho("Casal", true),
      criaTamanho("Queen", true),
      criaTamanho("King", true),
      criaTamanho("Super King", false),
    ],
    descricao: "Cobertor King",
    promocao: true,
    infoTecnicas: [
      "Composição: 100% poliéster.",
      "Dimensões: 2,20 x 2,40 metros.",
      "Lavagem: Lavar à máquina com água fria.",
      "Durável e de fácil manutenção.",
      "Material antialérgico.",
    ],
    infoAdicionais: [
      "Ideal para manter o aquecimento.",
      "Design moderno e elegante.",
      "Cores variadas para combinar com o ambiente.",
      "Conforto e suavidade ao toque.",
      "Perfeito para uso em camas king size.",
    ],
  },
  {
    id: 13,
    nome: "Terno Infantil Menino Batizado Social Juvenil Tam 10 12 14 E 16",
    cores: ["Branco", "Cinza", "Preto"],
    imagens: [
      "https://cdn.awsli.com.br/600x450/1953/1953797/produto/154151090/1-em9nj7bzmf.jpg",
    ],
    desconto: 17,
    preco: 285,
    categoria: "Infantil",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", false),
      criaTamanho("GG", true),
      criaTamanho("EG", false),
    ],
    descricao: "Terno Infantil Menino",
    promocao: true,
    infoTecnicas: [
      "Composição: 100% poliéster.",
      "Tamanhos: 10, 12, 14 e 16.",
      "Lavagem: Lavar a seco.",
      "Inclui: Blazer, calça e gravata.",
      "Forro: Totalmente forrado para conforto.",
    ],
    infoAdicionais: [
      "Ideal para ocasiões especiais e cerimônias.",
      "Design clássico e elegante.",
      "Ajuste confortável para crianças.",
      "Acabamento refinado e de alta qualidade.",
      "Facilmente combinável com camisas e sapatos sociais.",
    ],
  },
  {
    id: 14,
    nome: "Jaqueta de inverno algodão-acolchoado casaco",
    cores: ["Violeta", "Roxo", "Cinza", "Verde"],
    imagens: [
      "https://images.tcdn.com.br/img/img_prod/995322/jaqueta_de_inverno_roupas_femininas_algodao_acolchoado_casaco_moda_coreana_nova_casacos_de_pao_femin_787_1_c91b17ead9fe45b1c6838658245a8b1e.jpg",
    ],
    desconto: 15,
    preco: 341,
    categoria: "Feminino",
    opcao: [
      criaTamanho("P", false),
      criaTamanho("M", false),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", true),
    ],
    descricao: "Jaqueta de inverno",
    promocao: false,
    infoTecnicas: [
      "Composição: 60% algodão, 40% poliéster.",
      "Acolchoado: Forro interno de lã.",
      "Fechamento: Zíper frontal e botões.",
      "Capô removível.",
      "Lavagem: Lavar à máquina em ciclo delicado.",
    ],
    infoAdicionais: [
      "Ideal para climas frios.",
      "Design moderno e elegante.",
      "Disponível em várias cores.",
      "Boa isolação térmica.",
      "Perfeita para o inverno e viagens.",
    ],
  },
  {
    id: 15,
    nome: "Toalha De Rosto Veneza Mafratex Branco 75cmx 48 Cm",
    cores: ["Branco", "Violeta", "Roxo", "Cinza", "Vermelho", "Bege"],
    imagens: [
      "https://images.tcdn.com.br/img/img_prod/807302/toalha_rosto_new_veneza_perola_3295_1_7548ff783c2395a7239a9e193ddc8d4a.jpg",
    ],
    desconto: 30,
    preco: 29,
    categoria: "Outlet",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", false),
      criaTamanho("EG", false),
    ],
    descricao: "Toalha De Rosto",
    promocao: false,
    infoTecnicas: [
      "Composição: 100% algodão.",
      "Dimensões: 75 x 48 cm.",
      "Absorvente e macia.",
      "Lavagem: Lavar à máquina em água fria.",
      "Secagem: Secar à sombra.",
    ],
    infoAdicionais: [
      "Ideal para uso diário.",
      "Cores variadas e elegantes.",
      "Maciez e alta capacidade de absorção.",
      "Durável e de fácil manutenção.",
      "Perfeita para uso em casa ou em viagens.",
    ],
  },
  {
    id: 16,
    nome: "Conjunto Infantil Menino Moletom Jeans Marinho",
    cores: [
      "Branco",
      "Preto",
      "Cinza",
      "Violeta",
      "Roxo",
      "Azul",
      "Vermelho",    
      "Bege",
    ],
    imagens: [
      "https://10439028l.ha.azioncdn.net/img/2024/05/produto/14894/13134-casaco-malha-soft-moda-infantil-menino-graphite-frente.jpg?ims=fit-in/630x945/filters:fill(white)",
      "https://i.imgur.com/QGv5h5T.png", //resize
    ],
    desconto: 22,
    preco: 189,
    categoria: "Infantil",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", false),
    ],
    descricao: "Conjunto Infantil Menino",
    promocao: false,
    infoTecnicas: [
      "Composição: 80% algodão, 20% poliéster.",
      "Tamanhos disponíveis: P, M, G.",
      "Lavagem: Lavar à máquina em água fria.",
      "Material: Moletom macio e confortável.",
      "Detalhes: Cores sólidas e design moderno.",
    ],
    infoAdicionais: [
      "Ideal para uso casual e confortável.",
      "Ajuste confortável para crianças.",
      "Fácil de combinar com outros itens de vestuário.",
      "Perfeito para o clima frio.",
      "Design estiloso e prático.",
    ],
  },
  {
    id: 17,
    nome: "Toalha de Mesa Bordada Requinte Luxo cms - Argivai",
    cores: ["Branco", "Rosa", "Cinza", "Bordô"],
    imagens: [
      "https://www.romanceenxovais.com.br/octopus/design/images/92/products/b/luxo%20requinte%20luxo%20toalha%20de%20mesa%201.jpg",
    ],
    desconto: 22,
    preco: 199,
    categoria: "Outlet",

    opcao: [
      criaTamanho("1,20 x 1,30", false),
      criaTamanho("1,40 x 1,40", true),
      criaTamanho("1,50 x 1,50", true),
    ],
    descricao: "Toalha de Mesa Bordada",
    promocao: true,
    infoTecnicas: [
      "Composição: 100% poliéster.",
      "Dimensões: 150 x 150 cm.",
      "Detalhes: Bordado requintado.",
      "Lavagem: Lavar à máquina em água fria.",
      "Secagem: Secar à sombra.",
    ],
    infoAdicionais: [
      "Ideal para ocasiões especiais.",
      "Acabamento sofisticado.",
      "Design elegante e clássico.",
      "Fácil de combinar com diversos estilos de decoração.",
      "Perfeita para eventos e jantares.",
    ],
  },
  {
    id: 18,
    nome: "Jaqueta Masculina Young Royals",
    cores: ["Marron", "Preto"],
    imagens: [
      "https://todecacho.com.br/wp-content/uploads/2023/01/10-ideias-de-corte-de-cabelo-crespo-masculino.jpg",
    ],
    desconto: 31,
    preco: 478,
    categoria: "Masculino",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", false),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", true),
    ],
    descricao: "Jaqueta Masculina",
    promocao: true,
    infoTecnicas: [
      "Composição: 90% poliéster, 10% elastano.",
      "Tamanhos disponíveis: P, M, G.",
      "Fechamento: Zíper frontal.",
      "Lavagem: Lavar à máquina em ciclo delicado.",
      "Detalhes: Design moderno e estiloso.",
    ],
    infoAdicionais: [
      "Ideal para o uso diário e ocasiões especiais.",
      "Conforto e durabilidade.",
      "Estilo jovem e moderno.",
      "Ajuste perfeito com o zíper frontal.",
      "Perfeita para climas frios e casuais.",
    ],
  },
  {
    id: 19,
    nome: "Roupão De Banho Feminino Masculino Atoalhado Felpudo Quimono",
    cores: [
      "Branco",
      "Azul",
      "Violeta",
      "Roxo",
      "Cinza",
      "Vermelho",
      "Preto",
      "Amarelo",
      "Rosa",
    ],
    imagens: [
      "https://a-static.mlcdn.com.br/450x450/roupao-de-banho-feminino-masculino-atoalhado-felpudo-quimono-lepper/reiplastico/roupaomalibubordom/d457b62c488d5d7df4b543e7f8154d9b.jpeg",
    ],
    desconto: 13,
    preco: 189,
    categoria: "Outlet",
    opcao: [
      criaTamanho("P", false),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", false),
      criaTamanho("EG", true),
    ],
    descricao: "Roupão De Banho",
    promocao: false,
    infoTecnicas: [
      "Composição: 100% algodão.",
      "Design: Atoalhado e felpudo.",
      "Lavagem: Lavar à máquina em água fria.",
      "Secagem: Secar à sombra.",
      "Tamanho único.",
    ],
    infoAdicionais: [
      "Ideal para uso diário e após o banho.",
      "Material macio e absorvente.",
      "Variedade de cores disponíveis.",
      "Design unissex e elegante.",
      "Conforto e qualidade.",
    ],
  },
  {
    id: 20,
    nome: "Conjunto Infantil Criança Kit Completo, Calça e Camisa",
    cores: ["Branco","Azul", "Preto"],
    imagens: [
      "https://img.freepik.com/fotos-premium/menina-com-longos-cabelos-loiros-e-jeans_86390-987.jpg?w=360",
      "https://i.imgur.com/VWcfSHJ.png", //resize
    ],
    desconto: 20,
    preco: 150,
    categoria: "Infantil",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", false),
      criaTamanho("EG", true),
    ],
    descricao: "Conjunto Infantil",
    promocao: false,
    infoTecnicas: [
      "Composição: 100% algodão.",
      "Inclui: Calça e camisa.",
      "Lavagem: Lavar à máquina em água fria.",
      "Design: Casual e confortável.",
      "Tamanhos disponíveis: Diversos tamanhos infantis.",
    ],
    infoAdicionais: [
      "Ideal para o uso diário.",
      "Design moderno e prático.",
      "Fácil de combinar com outros itens.",
      "Confortável e durável.",
      "Perfeito para crianças em crescimento.",
    ],
  },
  {
    id: 21,
    nome: "Projetor",
    preco: 15000,
    imagens: [
      "https://i.imgur.com/bhJe5AE.png",
      "https://i.imgur.com/o5wIaIC.png",
    ],
    desconto: 70,
    descricao: "Projetor",
    cores: ["Branco", "Cinza", "Preto"],
    categoria: "Outlet",
    infoTecnicas: [
      "Resolução: 4K.",
      "Brilho: 3000 lumens.",
      "Tipo: LCD.",
      "Conectividade: HDMI, USB, Bluetooth.",
      "Compatibilidade: Suporta múltiplos formatos de vídeo.",
    ],
    infoAdicionais: [
      "Ideal para home theater e apresentações.",
      "Imagens de alta qualidade.",
      "Fácil instalação e uso.",
      "Diversas opções de conectividade.",
      "Compacto e eficiente.",
    ],
    promocao: true,
  },
  {
    id: 22,
    nome: "iPhone 15",
    preco: 16500,
    imagens: [
      "https://i.imgur.com/qpUxG0d.jpg",
      "https://i.imgur.com/Y9xyRkE.jpg",
    ],
    desconto: 65,
    descricao: "iPhone 15",
    cores: ["Azul", "Vermelho", "Preto", "Verde"],
    categoria: "Outlet",
    infoTecnicas: [
      'Tela: 6.1" Super Retina XDR.',
      "Processador: A17 Bionic.",
      "Armazenamento: 128GB/256GB/512GB.",
      "Câmera: Traseira tripla 48MP.",
      "Bateria: Até 20 horas de uso.",
    ],
    infoAdicionais: [
      "Desempenho avançado e rápido.",
      "Design elegante e moderno.",
      "Excelente qualidade de câmera.",
      "Sistema iOS com atualizações constantes.",
      "Disponível em várias cores atraentes.",
    ],
    promocao: true,
  },
  {
    id: 23,
    nome: "Notebook Gamer",
    preco: 5000,
    imagens: [
      "https://i.imgur.com/BTFVpuG.png",
      "https://i.imgur.com/c8PEJFQ.png",
    ],
    desconto: 15,
    descricao: "Notebook para jogos de última geração",
    cores: ["Preto", "Cinza"],
    categoria: "Outlet",
    infoTecnicas: [
      "Processador: Intel Core i9.",
      "Memória RAM: 32GB.",
      "Armazenamento: 1TB SSD.",
      "Placa de vídeo: NVIDIA RTX 3080.",
      'Tela: 17.3" Full HD.',
    ],
    infoAdicionais: [
      "Desempenho de alto nível para jogos.",
      "Tela grande e resolução excelente.",
      "Teclado retroiluminado.",
      "Sistema de resfriamento avançado.",
      "Design robusto e durável.",
    ],
    promocao: false,
  },
  {
    id: 24,
    nome: "Camiseta Básica",
    preco: 500,
    imagens: [
      "https://i.imgur.com/owwEBoY.png",
      "https://i.imgur.com/XlSq4Q6.png",
    ],
    desconto: 75,
    descricao: "Camiseta básica de algodão",
    cores: ["Branco", "Preto", "Cinza", "Verde", "Rosa"],
    categoria: "Feminino",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", true),
    ],
    infoTecnicas: [
      "Composição: 100% algodão.",
      "Tamanhos: P, M, G, GG.",
      "Lavagem: Lavar à máquina em água fria.",
      "Design: Simples e confortável.",
      "Tipo: Manga curta.",
    ],
    infoAdicionais: [
      "Ideal para o uso diário.",
      "Material respirável e confortável.",
      "Fácil de combinar com outros itens.",
      "Diversas cores básicas.",
      "Durável e de fácil manutenção.",
    ],
    promocao: true,
  },
  {
    id: 25,
    nome: "Tênis Esportivo ",
    preco: 8000,
    imagens: [
      "https://i.imgur.com/iDlolVv.png",
      "https://i.imgur.com/K6lBudo.png",
    ],
    desconto: 25,
    descricao: "Tênis para corrida e atividades físicas",
    cores: ["Azul", "Vermelho", "Preto", "Azul-Claro"],
    categoria: "Calçados",
    opcao: [
      {
        tamanho: "34",
        disponivel: true,
      },
      {
        tamanho: "35",
        disponivel: true,
      },
      criaTamanho("36", true),
      criaTamanho("37", false),
      criaTamanho("38", true),
      criaTamanho("39", false),
      criaTamanho("40", true),
      criaTamanho("41", true),
      criaTamanho("42", true),
      criaTamanho("43", false),
      criaTamanho("44", true),
      criaTamanho("45", true),
    ],
    infoTecnicas: [
      "Material: Mesh respirável.",
      "Sola: EVA com amortecimento.",
      "Tipo: Tênis de corrida.",
      "Tamanhos: Diversos tamanhos disponíveis.",
      "Fechamento: Cadarço.",
    ],
    infoAdicionais: [
      "Ideal para esportes e exercícios físicos.",
      "Design moderno e confortável.",
      "Boa ventilação e suporte ao pé.",
      "Leve e resistente.",
      "Disponível em várias cores vibrantes.",
    ],
    promocao: true,
  },
  {
    id: 26,
    nome: "Smartwatch",
    preco: 1200,
    imagens: [
      "https://i.imgur.com/muwHmf4.png",
      "https://i.imgur.com/Eq96OvD.png",//resize
      "https://i.imgur.com/TomxVjd.png",
    ],
    desconto: 30,
    descricao: "Relógio inteligente com monitoramento de saúde",
    cores: [
      "Preto",
      "Prata",
      "Rosa",
      "Verde",
      "Laranja",
      "Vermelho",
      "Cinza",
      "Azul-Claro",
    ],
    categoria: "Outlet",
    infoTecnicas: [
      'Tela: AMOLED 1.4".',
      "Conectividade: Bluetooth, Wi-Fi.",
      "Sensores: Monitoramento de batimentos cardíacos, sono e atividades.",
      "Bateria: Até 7 dias de uso.",
      "Compatibilidade: iOS e Android.",
    ],
    infoAdicionais: [
      "Monitoramento completo da saúde.",
      "Design elegante e personalizável.",
      "Ideal para atletas e entusiastas de fitness.",
      "Recebimento de notificações e chamadas.",
      "Resistente à água e poeira.",
    ],
    promocao: false,
  },
  {
    id: 27,
    nome: "Tablet Pro",
    preco: 2500,
    imagens: [
      "https://i.imgur.com/5H2eRKC.png",
      "https://i.imgur.com/Gz453bm.png",
    ],
    desconto: 10,
    descricao: "Tablet de alta performance para trabalho e lazer",
    cores: ["Branco", "Cinza", "Preto"],
    categoria: "Outlet",

    infoTecnicas: [
      'Tela: 12.9" Liquid Retina.',
      "Processador: Octa-core.",
      "Armazenamento: 256GB/512GB/1TB.",
      "Câmera: Traseira de 12MP e frontal de 7MP.",
      "Sistema: Android.",
    ],
    infoAdicionais: [
      "Ideal para trabalho e entretenimento.",
      "Desempenho rápido e eficiente.",
      "Tela grande com excelente resolução.",
      "Acessórios opcionais como teclado e stylus.",
      "Leve e portátil.",
    ],
    promocao: false,
  },
  {
    id: 28,
    nome: "Bicicleta Montanha",
    preco: 3000,
    imagens: [
      "https://i.imgur.com/ugYf3L0.png",
      "https://i.imgur.com/5ZUmEof.png",
    ],
    desconto: 20,
    descricao: "Bicicleta para trilhas e montanhas",
    cores: ["Cinza","Azul-Escuro", "Verde", "Preto", "Azul-Claro", "Azul"],
    categoria: "Outlet",
    opcao: [
      criaTamanho("Aro 12", false),
      criaTamanho("Aro 16", true),
      criaTamanho("Aro 20", false),
      criaTamanho("Aro 24", true),
      criaTamanho("Aro 26", true),
      criaTamanho("Aro 29", true),
    ],
    infoTecnicas: [
      "Estrutura: Alumínio.",
      "Suspensão: Dianteira e traseira.",
      "Marchas: 21 marchas.",
      "Rodas: 29 polegadas.",
      "Freios: Hidráulicos.",
    ],
    infoAdicionais: [
      "Ideal para trilhas e terrenos acidentados.",
      "Design robusto e durável.",
      "Boa absorção de impactos.",
      "Sistema de marchas eficiente.",
      "Confortável e estável.",
    ],
    promocao: false,
  },
  {
    id: 29,
    nome: "Jaqueta de Couro",
    preco: 1800,
    imagens: [
      "https://i.imgur.com/FUGf8KX.jpeg",
      "https://i.imgur.com/yABcEPH.png",
    ],
    desconto: 47,
    descricao: "Jaqueta de couro legítimo",
    cores: ["Preto", "Vinho", "Marrom"],
    categoria: "Masculino",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", false),
      criaTamanho("GG", true),
      criaTamanho("EG", true),
    ],
    infoTecnicas: [
      "Material: Couro legítimo.",
      "Forro: 100% poliéster.",
      "Fechamento: Zíper frontal.",
      "Tamanhos: Diversos tamanhos disponíveis.",
      "Detalhes: Acabamento refinado.",
    ],
    infoAdicionais: [
      "Elegante e durável.",
      "Design clássico e atemporal.",
      "Ideal para diversas ocasiões.",
      "Confortável e quente.",
      "Fácil de combinar com diferentes estilos de roupa.",
    ],
    promocao: true,
  },
  {
    id: 30,
    nome: "Cadeira Gamer",
    preco: 2200,
    imagens: [
      "https://i.imgur.com/BwRvVa8.png",
      "https://i.imgur.com/FTYNjpm.png",
    ],
    desconto: 25,
    descricao: "Cadeira ergonômica para jogos",
    cores: ["Preto", "Vermelho", "Azul"],
    categoria: "Outlet",
    infoTecnicas: [
      "Material: Couro sintético e espuma de alta densidade.",
      "Ajustes: Altura, inclinação e apoio de braço.",
      "Rodas: Giratórias e silenciosas.",
      "Peso máximo suportado: 150kg.",
      "Encosto: Ajustável e reclinável.",
    ],
    infoAdicionais: [
      "Design ergonômico para longas sessões de jogo.",
      "Alta durabilidade e resistência.",
      "Conforto aprimorado com ajustes personalizados.",
      "Estilo moderno e atraente.",
      "Fácil montagem e manutenção.",
    ],
    promocao: false,
  },
  {
    id: 31,
    nome: "Bermuda masculina Lacoste branco-bege",
    cores: ["Bege", "Branco", "Cinza"],
    imagens: [
      "https://checkout.gemegastore.com.br/resizer/view/false/false/true/false/8502.jpg",
    ],
    desconto: 20,
    preco: 399,
    categoria: "Masculino",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", false),
      criaTamanho("GG", true),
      criaTamanho("EG", false),
    ],
    descricao: "Bermuda masculina",
    promocao: false,
  },
  {
    id: 32,
    nome: "Bermuda Jeans Feminina",
    cores: ["Branco","Azul",  "Preto", "Cinza"],
    imagens: ["https://i.imgur.com/pOCTtnP.jpeg"],
    desconto: 18,
    preco: 169,
    categoria: "Feminino",
    opcao: [
      {
        tamanho: "34",
        disponivel: true,
      },
      {
        tamanho: "36",
        disponivel: true,
      },
      criaTamanho("38", true),
      criaTamanho("40", true),
      criaTamanho("42", false),
      criaTamanho("44", false),
      criaTamanho("46", true),
      criaTamanho("48", false),
      criaTamanho("50", true),
      criaTamanho("52", false),
      criaTamanho("54", true),
      criaTamanho("56", true),
      criaTamanho("58", false),
      criaTamanho("60", true),
      criaTamanho("62", false),
    ],
    descricao: "Bermuda Feminina",
    promocao: false,
  },
  {
    id: 33,
    nome: "Tennis infantil para menino escolar carrapixo",
    cores: ["Branco", "Azul", "Preto", "Cinza", "Azul-Claro"],
    imagens: [
      "https://a-static.mlcdn.com.br/450x450/tenis-infantil-para-menino-escolar-masculino-hard/hardcalcados/16016256489/cc6550123079b9c220609b3a5d34fa78.jpeg",
    ],
    desconto: 13,
    preco: 119,
    categoria: "Calçados",
    opcao: [
      {
        tamanho: "25",
        disponivel: true,
      },
      {
        tamanho: "26",
        disponivel: true,
      },
      criaTamanho("27", true),
      criaTamanho("28", true),
      criaTamanho("29", false),
      criaTamanho("30", true),
      criaTamanho("31", true),
      criaTamanho("32", false),
      criaTamanho("33", true),
      criaTamanho("34", false),
      criaTamanho("35", false),
      criaTamanho("36", true),
    ],
    descricao: "Tennis Infantil",
    promocao: true,
  },
  {
    id: 34,
    nome: "Tamanco salto alto grosso estilo retrô",
    cores: ["Bege", "Marrom", "Rosa"],
    imagens: [
      "https://acdn.mitiendanube.com/stores/003/711/885/products/tamanco-feminino-salto-alto-grosso-estilo-retro-vintage-9203-1-632d96e1c62d070ebb17100903600709-1024-1024.jpg",
    ],
    desconto: 14,
    preco: 188,
    categoria: "Calçados",
    opcao: [
      {
        tamanho: "34",
        disponivel: true,
      },
      {
        tamanho: "35",
        disponivel: true,
      },
      criaTamanho("36", true),
      criaTamanho("37", false),
      criaTamanho("38", true),
      criaTamanho("39", false),
      criaTamanho("40", false),
      criaTamanho("41", false),
      criaTamanho("42", false),
      criaTamanho("43", false),
      criaTamanho("44", true),
      criaTamanho("45", false),
    ],
    descricao: "Tamanco Feminino",
    promocao: true,
  },
  {
    id: 35,
    nome: "Fruteira Regia Com 2 Cestos e 1 Gaveta Dakar Com Branco",
    cores: ["Branco", "Marrom", "Cinza"],
    imagens: [
      "https://images.tcdn.com.br/img/img_prod/456619/fruteira_regia_com_2_cestos_e_1_gaveta_dakar_com_branco_moveis_fiorello_12357987_2_dcdadffce89664321e74f65d7d2964b5.jpg",
    ],
    desconto: 20,
    preco: 369,
    categoria: "Outlet",
    descricao: "Fruteira",
    promocao: false,
  },
  {
    id: 36,
    nome: "Jogo De Cama Bouti Lençol Casal King Com 04 Peças Estampado Patchwork Verde",
    cores: ["Branco", "Azul", "Verde", "Vinho", "Rosa"],
    imagens: [
      "https://images.tcdn.com.br/img/img_prod/875745/jogo_de_cama_bouti_lencol_casal_king_com_04_pecas_estampado_patchwork_verde_763_1_3af545ba579223ad0639688424be0b60.jpg",
    ],
    desconto: 9,
    preco: 109,
    categoria: "Outlet",
    opcao: [
      criaTamanho("Casal", true),
      criaTamanho("Queen", false),
      criaTamanho("Size", true),
      criaTamanho("Super Size", false),
    ],
    descricao: "Jogo de Cama",
    promocao: true,
  },
  {
    id: 37,
    nome: "Vestidos de noiva com fenda Branco",
    cores: ["Branco", "Marrom", "Rosa"],
    imagens: [
      "https://cdn0.casamentos.com.br/article-dress/5567/original/1280/jpg/m517655.jpeg",
    ],
    desconto: 14,
    preco: 2699,
    categoria: "Feminino",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", false),
    ],
    descricao: "Vestido de noiva",
    promocao: true,
  },
  {
    id: 38,
    nome: "Camiseta Masculina Seniors",
    cores: ["Branco", "Vermelho", "Amarelo", "Preto", "Verde", "Azul", "Bege"],
    imagens: [
      "https://static.vecteezy.com/ti/fotos-gratis/p2/9169955-retrato-de-homem-idoso-asiatico-vestir-camiseta-vermelha-com-bracos-cruzados-isolado-em-fundo-amarelo-foto.jpg",
    ],
    desconto: 20,
    preco: 79,
    categoria: "Masculino",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", false),
      criaTamanho("GG", true),
      criaTamanho("EG", false),
    ],
    descricao: "Camiseta Masculina",
    promocao: false,
  },
  {
    id: 39,
    nome: "Vestido Infantil Menina Long Manu",
    cores: ["Branco", "Bege", "Rosa", "Azul"],
    imagens: [
      "https://cdn.awsli.com.br/600x1000/650/650557/produto/206964648/manu-7wlqyn5ltb.jpeg",
    ],
    desconto: 12,
    preco: 89,
    categoria: "Infantil",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", false),
      criaTamanho("EG", false),
    ],
    descricao: "Vestido Infantil",
    promocao: true,
  },
  {
    id: 40,
    nome: "Vestido Feminino Clambell Space",
    cores: ["Branco", "Azul", "Preto", "Vermelho", "Verde"],
    imagens: [
      "https://http2.mlstatic.com/D_NQ_NP_2X_362511-MLB20560999416_012016-F.jpg",
    ],
    desconto: 23,
    preco: 257,
    categoria: "Feminino",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", false),
      criaTamanho("G", true),
      criaTamanho("GG", false),
      criaTamanho("EG", false),
    ],
    descricao: "Vestido Feminino",
    promocao: true,
  },
  {
    id: 41,
    nome: "Vestido Feminino Horizon Space",
    cores: ["Branco", "Azul", "Preto", "Vermelho", "Verde"],
    imagens: ["https://i.imgur.com/5XlvXYc.jpg"],
    desconto: 23,
    preco: 125,
    categoria: "Lançamento",
    opcao: [
      criaTamanho("P", false),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", false),
      criaTamanho("EG", false),
    ],
    descricao: "Vestido Feminino",
    promocao: true,
  },
  {
    id: 42,
    nome: "Camiseta Masculina",
    cores: [
      "Branco",
      "Azul",
      "Preto",
      "Vermelho",
      "Verde",
      "Marrom",
      "Amarelo",
      "AzulClaro",
      "Vinho",
      "Bege",
      "Rosa",
      "Cinza",
    ],
    imagens: ["https://i.imgur.com/GDik1rN.jpg"],
    desconto: 23,
    preco: 89,
    categoria: "Lançamento",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", true),
    ],
    descricao: "masculino",
    promocao: false,
  },
  {
    id: 43,
    nome: "Conjunto infantil masculino camiseta e bermuda Orleans",
    cores: ["Branco", "Azul", "Preto", "Laranja", "Verde"],
    imagens: ["https://i.imgur.com/WG5CvRn.jpg"],
    desconto: 13,
    preco: 175,
    categoria: "Lançamento",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", false),
      criaTamanho("EG", false),
    ],
    descricao: "Conjunto infantil masculino",
    promocao: true,
  },
  {
    id: 44,
    nome: "Cortina Gaze de Linho c/ Blackout 100% Wave p/ trilho de 4,5 m",
    cores: ["Branco", "Cinza", "Preto"],
    imagens: ["https://i.imgur.com/fkENjyU.jpg"],
    desconto: 27,
    preco: 1209,
    categoria: "Lançamento",
    opcao: [criaTamanho("4,00 x 2,60", true)],
    descricao: "Cortina Blackout",
    promocao: true,
  },
  {
    id: 45,
    nome: "Box de Vidro temperado para banheiro, com bordas coloridas",
    cores: ["Branco", "Bege", "Prata", "Preto"],
    imagens: ["https://i.imgur.com/WDsmSxI.jpg"],
    desconto: 12,
    preco: 399,
    categoria: "Lançamento",
    opcao: [
      criaTamanho("1,10 x 1,80", true),
      criaTamanho("1,50 x 1,80", true),
      criaTamanho("1,50 x 2,10", true),
      criaTamanho("2,10 x 2,80", true),
    ],
    descricao: "Box banheiro Infinite",
    promocao: true,
  },
  {
    id: 46,
    nome: "Conjunto feminino saia mais blusa Minor Harada",
    cores: ["Azul", "Cinza", "Vermelho", "Rosa", "Lilas"],
    imagens: ["https://i.imgur.com/PRbcRwl.jpg"],
    desconto: 23,
    preco: 189,
    categoria: "Lançamento",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", false),
      criaTamanho("EG", false),
    ],
    descricao: "Conjunto saia mais blusa",
    promocao: false,
  },
  {
    id: 47,
    nome: "Conjunto masculino infantil calça + camisa Young Royals",
    cores: ["Branco", "Azul", "Preto"],
    imagens: ["https://i.imgur.com/ggdHlB6.jpg"],
    desconto: 23,
    preco: 199,
    categoria: "Lançamento",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", false),
      criaTamanho("EG", false),
    ],
    descricao: "Conjunto masculino infantil",
    promocao: false,
  },
  {
    id: 48,
    nome: "Conjunto de roupas de verão meninas, top e shorts infantis",
    cores: ["Branco", "Azul", "Preto", "Lilas", "Rosa"],
    imagens: ["https://i.imgur.com/VOzopMB.jpg"],
    desconto: 14,
    preco: 122,
    categoria: "Lançamento",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", false),
    ],
    descricao: "Conjunto de roupas de verão meninas",
    promocao: false,
  },
  {
    id: 49,
    nome: "Calça Feminina Cintura Alta com Pala",
    cores: ["Branco", "Azul", "Preto", "Vermelho", "Verde"],
    imagens: ["https://i.imgur.com/mZUiqRY.jpg"],
    desconto: 21,
    preco: 288,
    categoria: "Lançamento",
    opcao: [
      {
        tamanho: "34",
        disponivel: true,
      },
      {
        tamanho: "36",
        disponivel: true,
      },
      criaTamanho("38", true),
      criaTamanho("40", true),
      criaTamanho("42", false),
      criaTamanho("44", true),
      criaTamanho("46", true),
      criaTamanho("48", false),
      criaTamanho("50", true),
      criaTamanho("52", false),
      criaTamanho("54", false),
      criaTamanho("56", false),
      criaTamanho("58", false),
      criaTamanho("60", false),
      criaTamanho("62", false),
    ],
    descricao: "Calça feminina",
    promocao: true,
  },
  {
    id: 50,
    nome: "Camisa Polo Masculina Concept, Azul / M",
    cores: ["Branco", "Azul", "Preto", "Vermelho", "Verde"],
    imagens: ["https://i.imgur.com/hAWkF29.jpg"],
    desconto: 15,
    preco: 109,
    categoria: "Lançamento",
    opcao: [
      criaTamanho("P", true),
      criaTamanho("M", true),
      criaTamanho("G", true),
      criaTamanho("GG", true),
      criaTamanho("EG", true),
    ],
    descricao: "Camisa polo masculina",
    promocao: true,
  },
  {
    id: 51,
    nome: "Tênis Nike Invincible 3 SE Masculino",
    cores: [
      "branco",
      "Cinza",
      "Vermelho",
      "Laranja",
      "Amarelo",
      "Verde",
      "Azul",
      "Azul-Claro",
      "Roxo",
      "Rosa",
      "Preto",
    ],
    imagens: [
      "https://i.imgur.com/t3MFp3z.png",
      "https://i.imgur.com/pQ3kbkA.png",
      "https://i.imgur.com/wc4Lu88.png",
      "https://i.imgur.com/q3CQ9vy.png",
      "https://i.imgur.com/Nr1wN1p.png",
      "https://i.imgur.com/jszvyJf.png",
    ],
    desconto: 20,
    preco: 625,
    categoria: "Calçados",
    opcao: [
      {
        tamanho: "34",
        disponivel: true,
      },
      {
        tamanho: "35",
        disponivel: true,
      },
      criaTamanho("36", false),
      criaTamanho("37", false),
      criaTamanho("38", false),
      criaTamanho("39", false),
      criaTamanho("40", false),
      criaTamanho("41", true),
      criaTamanho("42", false),
      criaTamanho("43", false),
      criaTamanho("44", false),
      criaTamanho("45", false),
    ],
    descricao: "Tênis Nike Invincible 3 SE Masculino",
    promocao: true,
    infoTecnicas: [
      "Material: Algodão e poliéster",
      "Tamanhos disponíveis: 2-3 anos, 4-5 anos, 6-7 anos",
      "Fechamento: Elástico e cordão",
      "Estilo: Casual",
      "Origem: Nacional",
    ],
    infoAdicionais: [
      "Tecido confortável lindo mais estiloso Ideal para o dia a dia Fácil de vestir e remover Tecido respirável e resistente Disponível em cores variadas,Conjunto confortável e estiloso Ideal para o dia a dia Fácil de vestir e remover  respirável e resistente Disponível",
      "Conjunto confortável otimo e estiloso Ideal para o dia a dia Fácil de vestir e remover Tecido respirável e resistente Disponível em cores variadas,Conjunto confortável e estiloso Ideal para o dia a dia Fácil de vestir e remover tambem respirável",
      "Conjunto confortável lindo e maravilhoso estiloso Ideal para o dia a dia Fácil de vestir e remover Tecido respirável e resistente Disponível em cores variadas,Conjunto confortável e estiloso Ideal para o dia a dia Fácil de vestir e remover e respirável e resistente Disponível em cores variadas",
      "Conjunto confortável bonito e estiloso Ideal para o dia a dia Fácil de vestir e remover Tecido respirável e resistente Disponível em cores variadas,Conjunto confortável e estiloso Ideal para o dia a dia Fácil de vestir e remover",
    ],
  },
];

export default produtos;
